services:
  - type: web
    name: ai-ecommerce-recommendation
    runtime: python
    buildCommand: bash render-build.sh
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT --timeout 180 src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
    plan: free
